# Exception_handling_examples
try, catch, else, finally, throw_using_raise, Nameerror

![try_catch_else](https://user-images.githubusercontent.com/82834644/116396633-773b0d80-a7da-11eb-8342-c192b8280223.PNG)

![eg2](https://user-images.githubusercontent.com/82834644/116396774-9d60ad80-a7da-11eb-8090-5314eb905bc8.PNG)
![finally](https://user-images.githubusercontent.com/82834644/116396777-9df94400-a7da-11eb-8ed4-8047c3d3f290.PNG)
![example1](https://user-images.githubusercontent.com/82834644/116396783-9fc30780-a7da-11eb-9c75-14660272d20f.PNG)
![nameError](https://user-images.githubusercontent.com/82834644/116396792-a18ccb00-a7da-11eb-8780-a619848c9f6a.PNG)
![raise](https://user-images.githubusercontent.com/82834644/116396799-a3568e80-a7da-11eb-842d-a5eb40ff758a.PNG)

